### ISSUE TITLE
Add User Agent Header

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-dotnet#83]
Add the user-agent request header to every call in this sdk.

Example:

headers: {
   Authorization: `Bearer ${ApiKey}`,
   "User-Agent": `novu/${sdk}@${version}`,
},

Why? (Context)

Having request headers in the SDKs will help us in monitoring which SDK is mostly used by the community and customers. It will help us make the decisions in the future on which SDKs to officially support in the future.

**Comment by toddb** [comment]
### Issue with the User-Agent Instruction  

The current ticket provides incorrect instructions for setting the `User-Agent` header in HTTP requests that won't work for the Http

```csharp
System.AggregateException
One or more errors occurred. (The format of value 'novu/novu-dotnet@0.0.0' is invalid.) (The format of value 'novu/novu-dotnet@0.0.0' is invalid.)
  Exception doesn't have a stacktrace

System.FormatException
The format of value 'novu/novu-dotnet@0.0.0' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
```

#### **Why the Instruction is Wrong**  
1. **Invalid User-Agent Format**: The `User-Agent` header should follow a standard format. Using `novu/novu-dotnet@0.0.0` is invalid due to the `@` symbol and four-segment version, which do not comply with HTTP standards.  

#### **Correct Solution**  
This will work:  

```
novu-dotnet/{nuget file version}
```

#### **Implementation Steps**  
To correctly retrieve the version:  

```csharp
using System.Reflection;

var version = Assembly
    .GetExecutingAssembly()
    .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?
    .InformationalVersion ?? "0.0.0"; // allow for detection of developers

var userAgent = $"novu-dotnet/{version}";
```
